### ISSUE TITLE
Changing env variable

### ISSUE THREAD

**Issue by slava110** [iulian-radu-at/insomnia-plugin-custom-generated-value#1]
Hi. I'm using Insomnia to send websocket messages with Chrome DevTools Protocol. In message it requires to specify message id which should be different for each message sent
```json
{
    "id": 0,
    "method": "METHOD_NAME",
    "params": {}
}
```
But in current version of your plugin it's impossible to modify environment variables using script
```js
"_js_message_id": [
    "return $$.message_id += 1;"
]
```
Reason:
https://github.com/iulian-radu-at/insomnia-plugin-custom-generated-value/blob/65190c36dcc4f52173c6f4b81b47d10edcfa07bc/src/main.ts#L93-L96
So I cannot increment value after each request. Do you think it's possible to add support for env var modification in custom scripts?

**Comment by iulianraduat** [comment]
Hi  @slava110,

Maybe returning random id's or using a script from a js file (you save the id in some external store) will help?

Cheers,
Iulian

**Comment by slava110** [comment]
Yep. Random id is sufficient. Thanks c:
I don't think it's possible to access filesystem from script. But still, problem solved
